FROM golang:alpine as builder
RUN mkdir /build 
ADD src /build/
WORKDIR /build 
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-extldflags "-static"' -o main .
FROM busybox
COPY --from=builder /build/main /app/
WORKDIR /app
CMD ["./main"]